### ISSUE TITLE
`\frac12` doesn’t render

### ISSUE THREAD

**Issue by sorsted** [ronkok/Temml#13]
In normal LaTeX, `\frac12` would render the same way as `\frac{1}{2}` (even though that is very bad syntax). But not so in TeMML. It yields an error instead. And `\frac12 3` yields the same as `\frac{12}{3}`.

**Comment by ronkok** [comment]
You have correctly described the default behavior. I've done this so that numbers will behave better semantically. Typing `123` will return `<mn>123</mn>` instead of `<mn>1</mn><mn>2</mn><mn>3</mn>`.

You can set Temml to `strict` mode and then it will act in the way that you suggest, treating numerals individually, just like LaTeX.

All this is described in the [documentation](https://temml.org/docs/en/supported.html#numbers).

I'll put a `strict` option in the demo page, but I do not intend to change the underlying code.

**Comment by ronkok** [comment]
@sorsted I've looked closer and found that I can have both consolidated `<mn>` elements and TeX-compliant number parsing. In fact, I've just released v0.10.4, which does that very thing. That resolves this issue.

Thank you for bringing this to my attention.
