### ISSUE TITLE
Option to suppress "xmlns=http://www.w3.org/1998/Math/MathML" attribute from each mathml output `<math>` element

### ISSUE THREAD

**Issue by universemaster** [ronkok/Temml#3]
Similarly, to #2, I believe a namespace attribute is unnecessary when embedded in HTML since the namespace is implied ( https://en.wikipedia.org/wiki/MathML#Embedding_MathML_in_HTML/XHTML_files ).

Again, (it seems) for many use cases including the namespace attribute is a waste of 43 characters/UTF8-bytes for every `<math>` element, which is a particularly nonoptimal in the case where many of the elements only contain one letter such as $x$.

For example, the github readme for this repository emphasises the lightweightness of temml at only 131 KB, but the inclusion of the namespace attribute on every math element of https://temml.org/docs/en/supported.html adds 1224 * 43 = about 53K extra characters/UTF8-bytes on that page (or would if it was server-side rendered).

---

I wonder also if we need the class attribute `class="temml"`.  Is this being used for anything that we cannot access via a selector using the `<math>` element?

**Comment by ronkok** [comment]
This issue has pro's and con's. You put the pro case well. On the other hand, this proposal increases the number of rendering options, which I would like to avoid, and the Temml repository would need twice as many CSS files, half of them with a namespace and half without.

And yes, a few users will target non-browser use cases. That issue has already come up in KaTeX.

`class='temml'` is necessary when a namespace is in use. Otherwise, probably not.

I'm leaning toward a yes on this question, but I'm going to think about it and do some testing before I commit myself.

**Comment by ronkok** [comment]
Done in version 0.2.2.
