### ISSUE TITLE
Could changes be contributed back to KaTeX?

### ISSUE THREAD

**Issue by waldyrious** [ronkok/Temml#48]
I'm curious if any of the MathML improvements and fixes made in this project could be reintegrated back into the KaTeX project. Would that be theoretically possible, or has the code diverged too much? Perhaps this would only be viable for a portion of the changes?

Just to be clear, I'm not suggesting that be done; I'm just trying to get a better understanding of the project, and making sure that this question gets an explicit answer in the issue tracker, in case anyone else wonders the same in the future.

**Comment by ronkok** [comment]
To answer your question,

1. A few parts of Temml cannot be back-ported to KaTeX.
2. Some parts could be back-ported with difficulty.
3. Some parts could be back-ported easily, if someone will do the review.

That last item needs some elaboration. Back when I was contributing code to KaTeX, there were four people who were very active in KaTeX development. Now, three of them are rarely seen there. That includes me and both of the people who did most of the reviews on my PRs.

The decline in activity happened slowly, but by [October 2021](https://github.com/KaTeX/KaTeX/pull/2460#issuecomment-954099048), I was frustrated with how long it took to get a review. It's gotten slower since then.

I'm pretty happy with Temml. I probably won't spend much effort trying to back-port items to KaTeX.
